spring:
  application:
    name: template-app
  datasource:
    hikari:
      connection-timeout: 60000
      validation-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
  profiles:
    active: local